/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VirtualImport } from './routes/virtual'
import { Route as ThrowErrorImport } from './routes/throw-error'
import { Route as RouterImport } from './routes/router'
import { Route as QueryImport } from './routes/query'
import { Route as IndexImport } from './routes/index'
import { Route as RouterSubRouteImport } from './routes/router.sub-route'
import { Route as RouterWildcardSplatImport } from './routes/router.wildcard.$'
import { Route as RouterPostPostIdImport } from './routes/router.post.$postId'

// Create Virtual Routes

const RouterLazyLoadLazyImport = createFileRoute('/router/lazy-load')()

// Create/Update Routes

const VirtualRoute = VirtualImport.update({
  id: '/virtual',
  path: '/virtual',
  getParentRoute: () => rootRoute,
} as any)

const ThrowErrorRoute = ThrowErrorImport.update({
  id: '/throw-error',
  path: '/throw-error',
  getParentRoute: () => rootRoute,
} as any)

const RouterRoute = RouterImport.update({
  id: '/router',
  path: '/router',
  getParentRoute: () => rootRoute,
} as any)

const QueryRoute = QueryImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RouterLazyLoadLazyRoute = RouterLazyLoadLazyImport.update({
  id: '/lazy-load',
  path: '/lazy-load',
  getParentRoute: () => RouterRoute,
} as any).lazy(() =>
  import('./routes/router.lazy-load.lazy').then((d) => d.Route),
)

const RouterSubRouteRoute = RouterSubRouteImport.update({
  id: '/sub-route',
  path: '/sub-route',
  getParentRoute: () => RouterRoute,
} as any)

const RouterWildcardSplatRoute = RouterWildcardSplatImport.update({
  id: '/wildcard/$',
  path: '/wildcard/$',
  getParentRoute: () => RouterRoute,
} as any)

const RouterPostPostIdRoute = RouterPostPostIdImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => RouterRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryImport
      parentRoute: typeof rootRoute
    }
    '/router': {
      id: '/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof RouterImport
      parentRoute: typeof rootRoute
    }
    '/throw-error': {
      id: '/throw-error'
      path: '/throw-error'
      fullPath: '/throw-error'
      preLoaderRoute: typeof ThrowErrorImport
      parentRoute: typeof rootRoute
    }
    '/virtual': {
      id: '/virtual'
      path: '/virtual'
      fullPath: '/virtual'
      preLoaderRoute: typeof VirtualImport
      parentRoute: typeof rootRoute
    }
    '/router/sub-route': {
      id: '/router/sub-route'
      path: '/sub-route'
      fullPath: '/router/sub-route'
      preLoaderRoute: typeof RouterSubRouteImport
      parentRoute: typeof RouterImport
    }
    '/router/lazy-load': {
      id: '/router/lazy-load'
      path: '/lazy-load'
      fullPath: '/router/lazy-load'
      preLoaderRoute: typeof RouterLazyLoadLazyImport
      parentRoute: typeof RouterImport
    }
    '/router/post/$postId': {
      id: '/router/post/$postId'
      path: '/post/$postId'
      fullPath: '/router/post/$postId'
      preLoaderRoute: typeof RouterPostPostIdImport
      parentRoute: typeof RouterImport
    }
    '/router/wildcard/$': {
      id: '/router/wildcard/$'
      path: '/wildcard/$'
      fullPath: '/router/wildcard/$'
      preLoaderRoute: typeof RouterWildcardSplatImport
      parentRoute: typeof RouterImport
    }
  }
}

// Create and export the route tree

interface RouterRouteChildren {
  RouterSubRouteRoute: typeof RouterSubRouteRoute
  RouterLazyLoadLazyRoute: typeof RouterLazyLoadLazyRoute
  RouterPostPostIdRoute: typeof RouterPostPostIdRoute
  RouterWildcardSplatRoute: typeof RouterWildcardSplatRoute
}

const RouterRouteChildren: RouterRouteChildren = {
  RouterSubRouteRoute: RouterSubRouteRoute,
  RouterLazyLoadLazyRoute: RouterLazyLoadLazyRoute,
  RouterPostPostIdRoute: RouterPostPostIdRoute,
  RouterWildcardSplatRoute: RouterWildcardSplatRoute,
}

const RouterRouteWithChildren =
  RouterRoute._addFileChildren(RouterRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/query': typeof QueryRoute
  '/router': typeof RouterRouteWithChildren
  '/throw-error': typeof ThrowErrorRoute
  '/virtual': typeof VirtualRoute
  '/router/sub-route': typeof RouterSubRouteRoute
  '/router/lazy-load': typeof RouterLazyLoadLazyRoute
  '/router/post/$postId': typeof RouterPostPostIdRoute
  '/router/wildcard/$': typeof RouterWildcardSplatRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/query': typeof QueryRoute
  '/router': typeof RouterRouteWithChildren
  '/throw-error': typeof ThrowErrorRoute
  '/virtual': typeof VirtualRoute
  '/router/sub-route': typeof RouterSubRouteRoute
  '/router/lazy-load': typeof RouterLazyLoadLazyRoute
  '/router/post/$postId': typeof RouterPostPostIdRoute
  '/router/wildcard/$': typeof RouterWildcardSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/query': typeof QueryRoute
  '/router': typeof RouterRouteWithChildren
  '/throw-error': typeof ThrowErrorRoute
  '/virtual': typeof VirtualRoute
  '/router/sub-route': typeof RouterSubRouteRoute
  '/router/lazy-load': typeof RouterLazyLoadLazyRoute
  '/router/post/$postId': typeof RouterPostPostIdRoute
  '/router/wildcard/$': typeof RouterWildcardSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/query'
    | '/router'
    | '/throw-error'
    | '/virtual'
    | '/router/sub-route'
    | '/router/lazy-load'
    | '/router/post/$postId'
    | '/router/wildcard/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/query'
    | '/router'
    | '/throw-error'
    | '/virtual'
    | '/router/sub-route'
    | '/router/lazy-load'
    | '/router/post/$postId'
    | '/router/wildcard/$'
  id:
    | '__root__'
    | '/'
    | '/query'
    | '/router'
    | '/throw-error'
    | '/virtual'
    | '/router/sub-route'
    | '/router/lazy-load'
    | '/router/post/$postId'
    | '/router/wildcard/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueryRoute: typeof QueryRoute
  RouterRoute: typeof RouterRouteWithChildren
  ThrowErrorRoute: typeof ThrowErrorRoute
  VirtualRoute: typeof VirtualRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueryRoute: QueryRoute,
  RouterRoute: RouterRouteWithChildren,
  ThrowErrorRoute: ThrowErrorRoute,
  VirtualRoute: VirtualRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/query",
        "/router",
        "/throw-error",
        "/virtual"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/query": {
      "filePath": "query.jsx"
    },
    "/router": {
      "filePath": "router.jsx",
      "children": [
        "/router/sub-route",
        "/router/lazy-load",
        "/router/post/$postId",
        "/router/wildcard/$"
      ]
    },
    "/throw-error": {
      "filePath": "throw-error.jsx"
    },
    "/virtual": {
      "filePath": "virtual.jsx"
    },
    "/router/sub-route": {
      "filePath": "router.sub-route.jsx",
      "parent": "/router"
    },
    "/router/lazy-load": {
      "filePath": "router.lazy-load.lazy.jsx",
      "parent": "/router"
    },
    "/router/post/$postId": {
      "filePath": "router.post.$postId.jsx",
      "parent": "/router"
    },
    "/router/wildcard/$": {
      "filePath": "router.wildcard.$.jsx",
      "parent": "/router"
    }
  }
}
ROUTE_MANIFEST_END */
